language: python
virtualenv:
  system_site_packages: true
python:
  - 2.7
before_install:
  - sudo apt-get install python-lxml
python:
  - 2.7
install:
  - pip install flake8
  - python setup.py install
script:
  - python setup.py test
  - flake8 .
